//
// Created by wangyz38535 on 2023/10/12.
//

#ifndef FIRESHOT_FIRESHOT_ERRNO_H
#define FIRESHOT_FIRESHOT_ERRNO_H

#define FIRE_SHOT_ERROR -1
#define FIRE_SHOT_OK 0
#define FIRE_SHOT_MKDIR_FAILED 1
#define FIRE_SHOT_OPEN_DIR_FAILED 2
#define FIRE_SHOT_INVALID_ARGUMENTS 3
#define FIRE_SHOT 100000





#endif //FIRESHOT_FIRESHOT_ERRNO_H
